import { DeterministicThemeItem, CANONICAL_CORE_PASSAGES } from './deterministicThemesData';

export const ALL_DETERMINISTIC_THEMES: DeterministicThemeItem[] = [
  // -------------------------------------------------------------
  // GRUPO 1: Ansiedade, medo e insegurança (15 temas)
  // -------------------------------------------------------------
  {
    id: 'ansiedade_preocupacao',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Ansiedade e preocupação excessiva',
    synonyms: ['ansiedade', 'estou ansioso', 'ansiosa', 'preocupacao excessiva', 'preocupado', 'angustia', 'inquietacao', 'nervosismo', 'mente acelerada'],
    dores: 'Incerteza, insegurança, aperto no peito, necessidade de controle, insônia',
    intencoes: 'Acolher a fragilidade emocional, transmitir serenidade e fortalecer a confiança na Providência divina',
    correlatos: ['descanso', 'cuidado', 'presenca_deus', 'confianca', 'paz'],
    cuidados: 'Não apresentar o sofrimento emocional como falta de fé ou fraqueza espiritual.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'medo_futuro',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo do futuro',
    synonyms: ['medo do futuro', 'incerteza do amanha', 'o que vai acontecer', 'futuro incerto', 'inseguranca sobre amanha'],
    dores: 'Sensação de desamparo diante do desconhecido, medo de perdas futuras',
    intencoes: 'Reafirmar a soberania e a fidelidade de Deus que já está no amanhã',
    correlatos: ['providencia', 'tempo_certo', 'protecao'],
    cuidados: 'Evitar determinismo fatalista; enfatizar a paternidade amorosa de Deus.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'medo_morrer',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de morrer',
    synonyms: ['medo de morrer', 'medo da morte', 'tanatofobia', 'angustia da morte', 'pavor de morrer'],
    dores: 'Pavor do fim, apego à vida terrena, incerteza sobre a eternidade',
    intencoes: 'Anunciar a vitória de Cristo sobre a morte e a promessa da ressurreição',
    correlatos: ['vida_eterna', 'salvacao', 'paz_cristo'],
    cuidados: 'Não minimizar o horror natural da morte, mas iluminá-lo com a Páscoa do Senhor.',
    passages: CANONICAL_CORE_PASSAGES.luto_ressurreicao,
  },
  {
    id: 'medo_perder_alguem_querido',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de perder alguém querido',
    synonyms: ['medo de perder alguem', 'medo de perder meus pais', 'medo de perder filho', 'medo de perder conjuge'],
    dores: 'Antecipação do luto, dependência afetiva, vulnerabilidade',
    intencoes: 'Confortar o coração e confiar as pessoas amadas ao amparo divino',
    correlatos: ['cuidado_deus', 'amparo', 'oracao_intercessao'],
    cuidados: 'Validar o amor e a estima sincera sem alimentar obsessões paralisantes.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'medo_fracassar',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de fracassar',
    synonyms: ['medo de fracassar', 'medo de errar', 'medo de falhar', 'inseguranca no trabalho', 'medo de nao conseguir'],
    dores: 'Cobrança excessiva, vergonha do julgamento alheio, paralisia de ação',
    intencoes: 'Recordar que o valor da pessoa não depende do sucesso mundano',
    correlatos: ['graca', 'humildade', 'recomeco'],
    cuidados: 'Não pregar teologia da prosperidade nem triunfalismo vazio.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'medo_ser_rejeitado',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de ser rejeitado',
    synonyms: ['medo de rejeicao', 'medo de ser rejeitado', 'rejeicao', 'medo de nao ser aceito', 'exclusao'],
    dores: 'Sensação de não pertencer, humilhação, medo do abandono',
    intencoes: 'Garantir o amor incondicional e o acolhimento perpétuo do Pai',
    correlatos: ['filiacao_divina', 'dignidade', 'acolhimento'],
    cuidados: 'Distinguir rejeição social da aceitação definitiva por Deus.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'medo_ficar_sozinho',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de ficar sozinho',
    synonyms: ['medo de ficar sozinho', 'medo da solidao', 'vou ficar so', 'abandono', 'isolamento'],
    dores: 'Vazio existencial, angústia do silêncio, carência de vínculos',
    intencoes: 'Revelar a presença consoladora do Espírito Santo e o valor da comunidade eclesial',
    correlatos: ['presenca_deus', 'comunidade', 'amizade'],
    cuidados: 'Não tratar a solidão apenas como problema moral, mas como sede de comunhão.',
    passages: CANONICAL_CORE_PASSAGES.solidao_amizade,
  },
  {
    id: 'medo_tomar_decisoes_erradas',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de tomar decisões erradas',
    synonyms: ['medo de errar na decisao', 'indecisao', 'duvida na escolha', 'nao sei o que fazer', 'discernimento dificil'],
    dores: 'Hesitação constante, medo de arrependimento, peso da responsabilidade',
    intencoes: 'Conceder espírito de sabedoria e prudência guiado pela oração',
    correlatos: ['sabedoria', 'discernimento', 'luz_espirito'],
    cuidados: 'Lembrar que a providência acompanha os que buscam a reta intenção.',
    passages: CANONICAL_CORE_PASSAGES.decisao_discernimento,
  },
  {
    id: 'inseguranca_mudancas',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Insegurança diante de mudanças',
    synonyms: ['inseguranca com mudanca', 'medo de mudar', 'mudanca de vida', 'nova fase', 'transicao'],
    dores: 'Perda de referências, instabilidade, desassossego',
    intencoes: 'Ancorar o coração na imutabilidade e fidelidade do Senhor',
    correlatos: ['fidelidade_deus', 'rocha_firme', 'novidade'],
    cuidados: 'Encorajar a abertura aos novos caminhos que Deus prepara.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'necessidade_controlar_tudo',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Necessidade de controlar tudo',
    synonyms: ['controlador', 'preciso controlar tudo', 'mania de controle', 'perfeccionismo ansioso', 'falta de entrega'],
    dores: 'Exaustão mental, frustração com o imprevisível, desgaste interpessoal',
    intencoes: 'Conduzir à santa entrega (abandono filial) nas mãos do Pai',
    correlatos: ['humildade', 'abandono_filial', 'paz_interior'],
    cuidados: 'Não confundir prudência e responsabilidade com obsessão por controle.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'pensamentos_inquietos',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Pensamentos que não dão descanso',
    synonyms: ['mente barulhenta', 'insonia por pensamentos', 'pensamento obsessivo', 'cabeca cheia', 'rumiando problemas'],
    dores: 'Cansaço psíquico, perda de foco, insônia e tensão',
    intencoes: 'Orar pela purificação da memória e pela paz que excede todo entendimento',
    correlatos: ['paz_mental', 'silencio', 'oracao_calma'],
    cuidados: 'Recomendar oração serena e apoio médico quando houver transtorno clínico.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'angustia_sem_motivo',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Angústia sem motivo claro',
    synonyms: ['angustia no peito', 'tristeza sem motivo', 'angustiado', 'aperto no coracao', 'angustia repentina'],
    dores: 'Desolação inexplicável, perda de energia, sensação de opressão',
    intencoes: 'Relembrar que Deus conhece o íntimo antes mesmo das palavras',
    correlatos: ['amparo', 'consolo', 'refugio'],
    cuidados: 'Nunca rotular estados de angústia como castigo divino.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'dificuldade_viver_presente',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Dificuldade de viver o presente',
    synonyms: ['preso no futuro', 'nao vivo o agora', 'ansioso pelo amanha', 'dificuldade de desfrutar o dia'],
    dores: 'Desconexão com a realidade imediata, perda dos dons cotidianos',
    intencoes: 'Valorizar a graça do dia de hoje como lugar do encontro com Deus',
    correlatos: ['graca_atual', 'vigilancia', 'gratidao'],
    cuidados: 'Enfatizar que Deus age no presente, no "agora" da salvação.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'medo_noticia_ruim',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Medo de receber uma notícia ruim',
    synonyms: ['medo de mas noticias', 'esperando o pior', 'pessimismo', 'noticia ruim', 'pressentimento ruim'],
    dores: 'Hipervigilância, sobressalto ao telefone, pessimismo crônico',
    intencoes: 'Firmar o coração no Salmo 112: "não temerá más notícias; seu coração é firme no Senhor"',
    correlatos: ['firmeza', 'protecao', 'escudo'],
    cuidados: 'Substituir o catastrophismo pela confiança orante.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },
  {
    id: 'coragem_enfrentar_medos',
    groupId: 1,
    groupName: 'Ansiedade, medo e insegurança',
    name: 'Coragem para enfrentar os próprios medos',
    synonyms: ['preciso de coragem', 'enfrentar o medo', 'superar o pavor', 'forca contra o medo', 'vencer o medo'],
    dores: 'Paralisia, sensação de covardia, autocrítica dolorosa',
    intencoes: 'Despertar a virtude cardinal da fortaleza pelo dom do Espírito',
    correlatos: ['fortaleza', 'vitoria', 'coragem'],
    cuidados: 'A coragem bíblica não é ausência de medo, mas confiança em Deus que caminha junto.',
    passages: CANONICAL_CORE_PASSAGES.ansiedade_confianca,
  },

  // -------------------------------------------------------------
  // GRUPO 2: Tristeza, sofrimento e esperança (15 temas)
  // -------------------------------------------------------------
  {
    id: 'tristeza_profunda',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Tristeza profunda',
    synonyms: ['tristeza profunda', 'muito triste', 'dor na alma', 'tristeza no coracao', 'abatimento'],
    dores: 'Desolação, perda de apetite pela vida, choro frequente',
    intencoes: 'Trazer bálsamo aos corações dilacerados e renovar a esperança',
    correlatos: ['consolo', 'balsamo', 'restauracao'],
    cuidados: 'Acolher a dor sem julgamentos morais nem frases feitas.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'depressao_amparo',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Depressão e busca de amparo',
    synonyms: ['depressao', 'estou com depressao', 'deprimido', 'deprimida', 'crise depressiva', 'amparo na depressao'],
    dores: 'Inércia severa, anedonia, desesperança profunda',
    intencoes: 'Sustentar na fragilidade e reafirmar que Deus jamais abandona os que sofrem',
    correlatos: ['luz_nas_trevas', 'cuidado_medico_e_oracao', 'amparo'],
    cuidados: 'Articular a oração com o tratamento psiquiátrico/psicológico adequado (Sirácida 38).',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'falta_vontade_viver',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Falta de vontade de continuar vivendo',
    synonyms: ['sem vontade de viver', 'quero sumir', 'cansado de viver', 'nao aguento mais viver', 'desejo de morrer'],
    dores: 'Sofrimento psíquico extremo, sensação de inutilidade e desamparo total',
    intencoes: 'Transmitir o valor sagrado da vida e o abraço incondicional de Jesus Cristo',
    correlatos: ['vida_sagrada', 'socorro_imediato', 'amor_redentor'],
    cuidados: 'Urgência pastoral: orientar a busca de ajuda especializada (CVV 188) e acolhimento humano caloroso.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'sensacao_nada_melhora',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Sensação de que nada vai melhorar',
    synonyms: ['nada vai melhorar', 'tudo da errado', 'sem saida', 'desesperanca', 'beco sem saida'],
    dores: 'Desânimo crônico, sensação de esforço inútil',
    intencoes: 'Reavivar a certeza de que Deus faz novas todas as coisas a seu tempo',
    correlatos: ['paciencia', 'renovacao', 'fidelidade'],
    cuidados: 'Não prometer facilidades mágicas, mas a companhia fiel de Deus no deserto.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'vazio_interior',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Vazio interior',
    synonyms: ['vazio interior', 'sinto um vazio', 'nada preenche', 'tedio existencial', 'alma vazia'],
    dores: 'Insatisfação com bens materiais, sede de plenitude',
    intencoes: 'Guiar a alma para a fonte de água viva que brota para a vida eterna',
    correlatos: ['agua_viva', 'intimidade_deus', 'plenitude'],
    cuidados: 'Mostrar que o coração humano foi feito para o infinito (Santo Agostinho).',
    passages: CANONICAL_CORE_PASSAGES.oracao_intimidade_deus,
  },
  {
    id: 'perda_sentido_vida',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Perda do sentido da vida',
    synonyms: ['perdi o sentido', 'qual o sentido da vida', 'para que viver', 'sem rumo', 'desorientado'],
    dores: 'Crise existencial, falta de propósito e direção',
    intencoes: 'Restabelecer a vocação ao amor e o plano eterno de salvação',
    correlatos: ['vocacao', 'proposito', 'plano_divino'],
    cuidados: 'Iluminar o sentido a partir do seguimento de Cristo e do serviço ao irmão.',
    passages: CANONICAL_CORE_PASSAGES.trabalho_vocacao,
  },
  {
    id: 'desanimo_comecar_dia',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Desânimo para começar o dia',
    synonyms: ['desanimo pela manha', 'sem forca para levantar', 'pesadelo acordar', 'cansaco matinal'],
    dores: 'Falta de energia física e espiritual ao acordar',
    intencoes: 'Oferecer orações da manhã e lembrar que as misericórdias se renovam a cada alvorecer',
    correlatos: ['aurora', 'renovo', 'forca_diaria'],
    cuidados: 'Encorajar pequenos passos na presença de Deus.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'choro_consolo',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Choro e necessidade de consolo',
    synonyms: ['choro muito', 'preciso chorar', 'preciso de consolo', 'lagrimas', 'coracao chorando'],
    dores: 'Dor acumulada, alívio pelo pranto, necessidade de acolhida',
    intencoes: 'Abençoar as lágrimas e proclamar a bem-aventurança dos que choram',
    correlatos: ['consolador', 'bem_aventuranca', 'abracoo_deus'],
    cuidados: 'Não reprimir o choro; o próprio Jesus chorou diante de Lázaro e de Jerusalém.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'sofrimento_silencioso',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Sofrimento que ninguém percebe',
    synonyms: ['sofrimento em segredo', 'ninguem ve minha dor', 'dor escondida', 'sorrio por fora e choro por dentro'],
    dores: 'Solidão na dor, vergonha de expor as feridas, máscara social',
    intencoes: 'Lembrar que o Pai vê em segredo e guarda cada lágrima em seu odre',
    correlatos: ['olhar_deus', 'compreensao', 'intimidade'],
    cuidados: 'Incentivar a partilha com amigos e diretores espirituais de confiança.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'fundo_do_poco',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Sensação de estar no fundo do poço',
    synonyms: ['fundo do poco', 'estou destruido', 'cheguei ao limite', 'sem saida', 'no chao'],
    dores: 'Esgotamento total, perda de todas as defesas humanas',
    intencoes: 'Reafirmar que a mão de Deus alcança as maiores profundezas',
    correlatos: ['socorro_urgente', 'braco_forte', 'resgate'],
    cuidados: 'Citar os Salmos de clamor profundo (De profundis / Sl 130).',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'esperanca_tempos_dificeis',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Esperança em tempos difíceis',
    synonyms: ['esperanca', 'ter esperanca', 'dias melhores', 'manter a fe', 'esperar em deus'],
    dores: 'Desgaste por tribulações prolongadas',
    intencoes: 'Ancorar a virtude teologal da esperança no Cristo Ressuscitado',
    correlatos: ['ancora_alma', 'vitoria_cristo', 'perseveranca'],
    cuidados: 'Diferenciar o mero otimismo psicológico da Esperança cristã sobrenatural.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'alegria_em_dificuldades',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Alegria em meio às dificuldades',
    synonyms: ['alegria nas provacoes', 'paz na tempestade', 'alegria cristã', 'sorrir na dor'],
    dores: 'Tentação de azedume e amargura diante dos revezes da vida',
    intencoes: 'Testemunhar a alegria profunda do Evangelho que não depende de circunstâncias favoráveis',
    correlatos: ['gozo_espirito', 'paz_profunda', 'louvor'],
    cuidados: 'Não impor fingimento de felicidade exterior nem negar as dores reais.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'forca_atravessar_crise',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Força para atravessar uma crise',
    synonyms: ['forca na crise', 'superar crise', 'momento dificil', 'crise na vida', 'aguentar a tempestade'],
    dores: 'Sobrecarga de problemas simultâneos, sensação de cansaço extremo',
    intencoes: 'Ministrar a fortaleza de Deus que sustenta os passos na noite escura',
    correlatos: ['sustento', 'resiliencia_fe', 'graca_suficiente'],
    cuidados: 'Lembrar que na fraqueza humana a graça se manifesta com maior fulgor.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },
  {
    id: 'recomecar_perder_tudo',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Recomeçar depois de perder tudo',
    synonyms: ['perdi tudo', 'recomecar do zero', 'reconstruir a vida', 'falencia e recomeco', 'perda total'],
    dores: 'Desorientação material e emocional após grande ruína ou tragédia',
    intencoes: 'Inspirar a reconstrução com base na fé viva e no exemplo de Jó e dos santos',
    correlatos: ['reconstrucao', 'paciencia_jo', 'nova_vida'],
    cuidados: 'Destacar que a dignidade humana diante de Deus permanece intacta.',
    passages: CANONICAL_CORE_PASSAGES.trabalho_vocacao,
  },
  {
    id: 'sentido_no_sofrimento',
    groupId: 2,
    groupName: 'Tristeza, sofrimento e esperança',
    name: 'Encontrar sentido no sofrimento',
    synonyms: ['por que sofremos', 'sentido da dor', 'valor do sofrimento', 'dor redentora', 'carregar a cruz'],
    dores: 'Incompreensão do mistério do mal, escândalo com a dor inocente',
    intencoes: 'Unir os sofrimentos à Cruz redentora de Jesus (Salvifici Doloris)',
    correlatos: ['cruz_redentora', 'redencao', 'oferta_vida'],
    cuidados: 'Nunca exaltar o sofrimento em si mesmo, mas o amor com que Cristo redimiu a dor.',
    passages: CANONICAL_CORE_PASSAGES.tristeza_esperanca,
  },

  // -------------------------------------------------------------
  // GRUPO 3: Autoestima, identidade e comparação (15 temas)
  // -------------------------------------------------------------
  {
    id: 'sentir_sem_valor',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Sentir-se sem valor',
    synonyms: ['nao valho nada', 'me sinto inutil', 'sem valor', 'desvalorizado', 'ninguem se importa comigo'],
    dores: 'Autoimagem destruída, sensação de ser um peso para os outros',
    intencoes: 'Proclamar que cada ser humano é comprado pelo sangue precioso de Cristo',
    correlatos: ['preciosidade', 'dignidade_filho_deus', 'amor_incondicional'],
    cuidados: 'Enfatizar a dignidade ontológica concedida na Criação e no Batismo.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'sentir_insuficiente',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Sentir-se insuficiente',
    synonyms: ['nunca sou suficiente', 'insuficiente', 'nao dou conta', 'incapaz', 'sensacao de insuficiencia'],
    dores: 'Frustração crônica com o próprio desempenho, medo de desapontar',
    intencoes: 'Lembrar que a suficiência vem de Deus e não das forças humanas',
    correlatos: ['graca_divina', 'descanso', 'humildade'],
    cuidados: 'Diferenciar responsabilidade saudável de cobrança obsessiva por perfeição.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'comparacao_com_outros',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Comparar-se com os outros',
    synonyms: ['me comparo com todos', 'inveja dos outros', 'comparacao', 'a vida dos outros e melhor', 'inferioridade'],
    dores: 'Amargura, inveja disfarçada, perda da própria singularidade',
    intencoes: 'Reconhecer o caminho único e irrepetível que Deus traçou para cada filho',
    correlatos: ['singularidade', 'vocacao_propria', 'gratidao'],
    cuidados: 'Desconstruir a ilusão dos filtros e das aparências sociais.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'vergonha_aparencia',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Vergonha da própria aparência',
    synonyms: ['vergonha do corpo', 'me acho feio', 'me acho feia', 'aparencia fisica', 'complexo de aparencia'],
    dores: 'Timidez excessiva, isolamento social, ódio pelo próprio corpo',
    intencoes: 'Redescobrir a beleza da pessoa humana como templo do Espírito Santo',
    correlatos: ['templo_espirito', 'beleza_interior', 'criacao_divina'],
    cuidados: 'Valorizar o corpo como dom sem cair na idolatria estética mundana.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'aceitar_proprio_corpo',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Dificuldade de aceitar o próprio corpo',
    synonyms: ['rejeicao do corpo', 'nao gosto de mim', 'aceitacao corporal', 'odio ao corpo'],
    dores: 'Sofrimento com limitações físicas, marcas ou mudanças da idade',
    intencoes: 'Reconciliar-se com o próprio corpo em espírito de gratidão ao Criador',
    correlatos: ['gratidao_corpo', 'respeito', 'integridade'],
    cuidados: 'Promover saúde e autocuidado sem cair no culto ao corpo.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'necessidade_aprovacao',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Necessidade de aprovação dos outros',
    synonyms: ['preciso de elogio', 'medo de desagradar', 'agradar a todos', 'dependente de aprovacao'],
    dores: 'Perda de autenticidade, submissão a exigências abusivas',
    intencoes: 'Buscar agradar primeiramente a Deus com liberdade interior e consciência reta',
    correlatos: ['liberdade_filhos_deus', 'reta_intencao', 'autenticidade'],
    cuidados: 'Evitar o desprezo soberbo pelos outros; buscar a reta intenção evangélica.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'sentir_se_fracasso',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Sentir-se um fracasso',
    synonyms: ['sou um fracasso', 'fracassado', 'fracassada', 'tudo que faco da errado', 'derrotado'],
    dores: 'Desespero diante de erros passados, autodesprezo',
    intencoes: 'Apresentar a misericórdia que reergue os caídos e renova as oportunidades',
    correlatos: ['misericordia', 'reerguimento', 'segunda_chance'],
    cuidados: 'Mostrar que aos olhos de Deus nenhum erro define a identidade definitiva do homem.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'culpar_se_por_tudo',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Culpar-se por tudo',
    synonyms: ['a culpa e toda minha', 'me culpo por tudo', 'remorso constante', 'autoculpabilizacao'],
    dores: 'Remorso paralisante, assumir responsabilidade por erros de terceiros',
    intencoes: 'Libertar do escrúpulo mórbido e discernir a verdadeira responsabilidade com paz',
    correlatos: ['libertacao_culpa', 'paz_consciencia', 'misericordia'],
    cuidados: 'Distinguir arrependimento salutar de culpa neurótica autodestrutiva.',
    passages: CANONICAL_CORE_PASSAGES.perdao_misericordia,
  },
  {
    id: 'perfeccionismo_autocobranca',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Perfeccionismo e autocobrança',
    synonyms: ['muito perfeccionista', 'exijo demais de mim', 'autocobranca excessiva', 'rigidez comigo mesmo'],
    dores: 'Incapacidade de relaxar, frustração diante de qualquer falha menor',
    intencoes: 'Acolher a pedagogia da paciência de Deus que caminha com a nossa fragilidade',
    correlatos: ['paciencia_consigo', 'humildade_crista', 'graca'],
    cuidados: 'Não confundir a santidade com perfeccionismo obsessivo.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'reconhecer_qualidades',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Dificuldade de reconhecer as próprias qualidades',
    synonyms: ['nao vejo qualidades em mim', 'acho que nao tenho dons', 'cegueira dos dons', 'falsa humildade'],
    dores: 'Sentimento de nulidade, vergonha de colocar talentos a serviço',
    intencoes: 'Agradecer pelos dons recebidos e colocá-los com humildade a serviço da comunidade',
    correlatos: ['parabola_talentos', 'servico', 'gratidao'],
    cuidados: 'Reconhecer os dons como presentes de Deus não é soberba, mas justiça e louvor.',
    passages: CANONICAL_CORE_PASSAGES.trabalho_vocacao,
  },
  {
    id: 'inferior_pobreza',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Sentir-se inferior por ser pobre',
    synonyms: ['vergonha de ser pobre', 'inferior pela renda', 'humilhado pela pobreza', 'falta de condicao financeira'],
    dores: 'Humilhação social, marginalização, exclusão',
    intencoes: 'Exaltar a dignidade régia dos pobres aos olhos de Deus e a bem-aventurança evangélica',
    correlatos: ['bem_aventurados_pobres', 'dignidade_humana', 'justica'],
    cuidados: 'Denunciar o preconceito social e recordar que Jesus escolheu a simplicidade de Nazaré.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'inferior_escolaridade',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Sentir-se inferior por ter pouca escolaridade',
    synonyms: ['pouco estudo', 'vergonha de nao ter diploma', 'analfabeto funcional', 'sem estudo'],
    dores: 'Complexo de inferioridade intelectual, medo de se expressar',
    intencoes: 'Celebrar a sabedoria dos humildes que Deus revela aos pequeninos',
    correlatos: ['sabedoria_pequeninos', 'dignidade', 'verdade'],
    cuidados: 'Lembrar que os Apóstolos eram pescadores simples cheios do Espírito Santo.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'descobrir_identidade',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Descobrir a própria identidade',
    synonyms: ['quem sou eu', 'descobrir quem sou', 'busca de identidade', 'crise de identidade'],
    dores: 'Desorientação interior, viver em função das expectativas alheias',
    intencoes: 'Encontrar a verdadeira identidade no coração de Deus como filho amado',
    correlatos: ['filiacao_divina', 'vocacao', 'verdade'],
    cuidados: 'Mostrar que a resposta mais profunda para "quem sou eu" está no Batismo.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'reconhecer_dignidade',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Reconhecer a própria dignidade',
    synonyms: ['minha dignidade', 'sou imagem de deus', 'respeito a mim mesmo', 'valor humano'],
    dores: 'Tratamentos humilhantes sofridos no passado, autodesvalorização',
    intencoes: 'Contemplar a dignidade inalienável de ser criado à imagem e semelhança de Deus',
    correlatos: ['imagem_semelhanca', 'redencao', 'honra'],
    cuidados: 'Reafirmar que nenhuma ofensa alheia pode apagar o selo de Deus na alma.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
  {
    id: 'aceitar_limitacoes',
    groupId: 3,
    groupName: 'Autoestima, identidade e comparação',
    name: 'Aceitar as próprias limitações',
    synonyms: ['aceitar meus limites', 'minhas fraquezas', 'nao consigo tudo', 'paciencia com limites'],
    dores: 'Frustração diante da própria fragilidade física, psíquica ou moral',
    intencoes: 'Acolher a virtude da santa humildade e depender da graça de Cristo',
    correlatos: ['humildade', 'graca_na_fraqueza', 'sabedoria'],
    cuidados: 'A aceitação dos limites não é comodismo, mas realismo e sabedoria espiritual.',
    passages: CANONICAL_CORE_PASSAGES.autoestima_dignidade,
  },
];
