/**
 * Catálogo Determinístico Integral de 300 Temas Pastorais em 20 Grupos
 * Estrutura conforme diretrizes do Magistério e Exegese Católica.
 */

export interface ThemePassageRef {
  book: string;
  chapter: number;
  verseStart: number;
  verseEnd?: number;
  text: string;
}

export interface DeterministicThemeItem {
  id: string;
  groupId: number;
  groupName: string;
  name: string;
  synonyms: string[];
  dores: string;
  intencoes: string;
  correlatos: string[];
  cuidados: string;
  passages: ThemePassageRef[];
}

export const THEME_GROUPS = [
  { id: 1, name: 'Ansiedade, medo e insegurança' },
  { id: 2, name: 'Tristeza, sofrimento e esperança' },
  { id: 3, name: 'Autoestima, identidade e comparação' },
  { id: 4, name: 'Solidão, pertencimento e amizade' },
  { id: 5, name: 'Amor, namoro e discernimento afetivo' },
  { id: 6, name: 'Casamento e vida conjugal' },
  { id: 7, name: 'Sexualidade, desejo e intimidade' },
  { id: 8, name: 'Família, pais e filhos' },
  { id: 9, name: 'Maternidade, paternidade e chegada dos filhos' },
  { id: 10, name: 'Luto, saudade e despedidas' },
  { id: 11, name: 'Saúde, doença e cuidado' },
  { id: 12, name: 'Trabalho, estudo e vocação' },
  { id: 13, name: 'Dinheiro, necessidades e bens materiais' },
  { id: 14, name: 'Perdão, culpa e reconciliação' },
  { id: 15, name: 'Raiva, convivência e comunicação' },
  { id: 16, name: 'Hábitos, vícios e liberdade interior' },
  { id: 17, name: 'Fé, oração e relacionamento com Deus' },
  { id: 18, name: 'Vida católica e caminhada espiritual' },
  { id: 19, name: 'Justiça, proteção e responsabilidade com o próximo' },
  { id: 20, name: 'Decisões, mudanças e amadurecimento' },
];

// Helper para gerar conjuntos pastorais canônicos de 12 passagens equilibradas por categoria
export const CANONICAL_CORE_PASSAGES: Record<string, ThemePassageRef[]> = {
  ansiedade_confianca: [
    { book: 'Filipenses', chapter: 4, verseStart: 6, verseEnd: 7, text: 'Não vos inquieteis com nada! Em todas as circunstâncias apresentai a Deus as vossas preocupações.' },
    { book: '1 Pedro', chapter: 5, verseStart: 7, text: 'Lançai sobre Ele todas as vossas preocupações, porque Ele tem cuidado de vós.' },
    { book: 'Mateus', chapter: 6, verseStart: 34, text: 'Não vos preocupeis com o dia de amanhã, pois o dia de amanhã terá as suas preocupações. A cada dia basta o seu fardo.' },
    { book: 'Salmos', chapter: 94, verseStart: 19, text: 'Quando as preocupações se multiplicam dentro de mim, tuas consolações alegram a minha alma.' },
    { book: 'Isaías', chapter: 41, verseStart: 10, text: 'Não temas, porque eu estou contigo; não te angusties, porque eu sou o teu Deus; eu te fortaleço e te ajudo.' },
    { book: 'João', chapter: 14, verseStart: 27, text: 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.' },
    { book: 'Salmos', chapter: 23, verseStart: 1, verseEnd: 2, text: 'O Senhor é meu pastor, nada me faltará. Em verdes pastagens me faz repousar.' },
    { book: 'Salmos', chapter: 56, verseStart: 4, text: 'No dia em que o medo me assaltar, em ti porei a minha inteira confiança.' },
    { book: 'Lucas', chapter: 12, verseStart: 22, text: 'Não andeis desassossegados quanto à vossa vida, pelo que haveis de comer, nem quanto ao corpo, pelo que haveis de vestir.' },
    { book: 'Provérbios', chapter: 3, verseStart: 5, verseEnd: 6, text: 'Confia no Senhor de todo o teu coração e não te apoies na tua própria inteligência.' },
    { book: 'Josué', chapter: 1, verseStart: 9, text: 'Sê forte e corajoso; não temas nem te apavores, porque o Senhor teu Deus está contigo por onde quer que andares.' },
    { book: 'Romanos', chapter: 8, verseStart: 31, text: 'Se Deus é por nós, quem será contra nós?' },
  ],
  tristeza_esperanca: [
    { book: 'Salmos', chapter: 34, verseStart: 19, text: 'O Senhor está perto dos corações contritos e salva os de espírito abatido.' },
    { book: 'Mateus', chapter: 11, verseStart: 28, text: 'Vinde a mim, todos vós que estais cansados e sobrecarregados, e eu vos darei descanso.' },
    { book: 'Apocalipse', chapter: 21, verseStart: 4, text: 'Ele enxugará toda lágrima dos seus olhos; não haverá mais morte, nem luto, nem pranto, nem dor.' },
    { book: '2 Coríntios', chapter: 1, verseStart: 3, verseEnd: 4, text: 'Bendito seja o Deus de toda a consolação, que nos consola em todas as nossas tribulações.' },
    { book: 'Salmos', chapter: 30, verseStart: 6, text: 'O pranto pode durar uma noite, mas a alegria vem ao romper da manhã.' },
    { book: 'Isaías', chapter: 40, verseStart: 29, text: 'Ele dá força ao cansado e multiplica o vigor ao que não tem forças.' },
    { book: 'Salmos', chapter: 42, verseStart: 12, text: 'Por que estás abatida, ó minha alma? Espera em Deus, pois ainda o louvarei, meu auxílio e meu Deus.' },
    { book: 'João', chapter: 16, verseStart: 33, text: 'No mundo haveis de ter aflições. Coragem! Eu venci o mundo.' },
    { book: 'Romanos', chapter: 15, verseStart: 13, text: 'O Deus da esperança vos encha de toda a alegria e paz na vossa fé.' },
    { book: 'Salmos', chapter: 126, verseStart: 5, text: 'Os que semeiam entre lágrimas colherão com júbilo.' },
    { book: 'Lamentações', chapter: 3, verseStart: 22, verseEnd: 23, text: 'As misericórdias do Senhor são a causa de não sermos consumidos; renovam-se a cada manhã.' },
    { book: '1 Tessalonicenses', chapter: 5, verseStart: 16, verseEnd: 18, text: 'Alegrai-vos sempre. Orai sem cessar. Em tudo dai graças.' },
  ],
  autoestima_dignidade: [
    { book: 'Isaías', chapter: 43, verseStart: 4, text: 'És precioso aos meus olhos, és honrado e eu te amo.' },
    { book: 'Salmos', chapter: 139, verseStart: 14, text: 'Eu te louvo porque fui feito de modo tão admirável; maravilhosas são as tuas obras.' },
    { book: '1 João', chapter: 3, verseStart: 1, text: 'Vede que grande amor o Pai nos concedeu: sermos chamados filhos de Deus, e nós o somos!' },
    { book: 'Efésios', chapter: 2, verseStart: 10, text: 'Pois somos obra sua, criados em Cristo Jesus para as boas obras.' },
    { book: '1 Samuel', chapter: 16, verseStart: 7, text: 'O homem olha a aparência, mas o Senhor olha o coração.' },
    { book: 'Gálatas', chapter: 2, verseStart: 20, text: 'Vivo na fé do Filho de Deus, que me amou e se entregou por mim.' },
    { book: 'Lucas', chapter: 12, verseStart: 7, text: 'Até os cabelos da vossa cabeça estão todos contados. Não tenhais medo; valeis mais do que muitos pardais.' },
    { book: 'Romanos', chapter: 8, verseStart: 38, verseEnd: 39, text: 'Nada nos poderá separar do amor de Deus que está em Cristo Jesus.' },
    { book: 'Jeremias', chapter: 1, verseStart: 5, text: 'Antes de formar-te no seio materno, eu já te conhecia e te consagrei.' },
    { book: '2 Coríntios', chapter: 12, verseStart: 9, text: 'Basta-te a minha graça, porque a força se aperfeiçoa na fraqueza.' },
    { book: 'Sofonias', chapter: 3, verseStart: 17, text: 'O Senhor teu Deus está no meio de ti; Ele exultará de alegria por ti e renovar-te-á com seu amor.' },
    { book: 'Salmos', chapter: 8, verseStart: 5, verseEnd: 6, text: 'Fizeste o ser humano pouco menor que os anjos, coroando-o de glória e de honra.' },
  ],
  solidao_amizade: [
    { book: 'Salmos', chapter: 27, verseStart: 10, text: 'Ainda que meu pai e minha mãe me abandonem, o Senhor me acolherá.' },
    { book: 'Eclesiastes', chapter: 4, verseStart: 9, verseEnd: 10, text: 'Melhor é estarem dois juntos do que um só. Se um cair, o companheiro levanta-o.' },
    { book: 'Provérbios', chapter: 17, verseStart: 17, text: 'O amigo ama em todo o tempo; e na angústia nasce o irmão.' },
    { book: 'João', chapter: 15, verseStart: 15, text: 'Já não vos chamo servos, mas chamo-vos amigos, porque vos dei a conhecer tudo o que ouvi de meu Pai.' },
    { book: 'Mateus', chapter: 28, verseStart: 20, text: 'Eis que estou convosco todos os dias, até o fim dos tempos.' },
    { book: 'Eclesiástico', chapter: 6, verseStart: 14, text: 'Amigo fiel é poderoso refúgio: quem o encontrou, encontrou um tesouro.' },
    { book: 'Salmos', chapter: 68, verseStart: 7, text: 'Deus dá um lar aos desamparados e conduz os cativos à liberdade.' },
    { book: 'Romanos', chapter: 12, verseStart: 10, text: 'Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra.' },
    { book: 'Hebreus', chapter: 13, verseStart: 5, text: 'De maneira alguma te deixarei, nunca, jamais te abandonarei.' },
    { book: 'Provérbios', chapter: 27, verseStart: 9, text: 'O perfume e o incenso alegram o coração; a doçura de um amigo consola a alma.' },
    { book: '1 João', chapter: 4, verseStart: 7, text: 'Amados, amemo-nos uns aos outros, porque o amor procede de Deus.' },
    { book: 'Salmos', chapter: 133, verseStart: 1, text: 'Oh! Como é bom e agradável viverem os irmãos em perfeita união!' },
  ],
  amor_matrimonio: [
    { book: '1 Coríntios', chapter: 13, verseStart: 4, verseEnd: 7, text: 'O amor é paciente, o amor é bondoso; tudo sofre, tudo crê, tudo espera, tudo suporta.' },
    { book: 'Efésios', chapter: 5, verseStart: 25, text: 'Maridos, amai as vossas mulheres, como Cristo amou a Igreja e se entregou por ela.' },
    { book: 'Gênesis', chapter: 2, verseStart: 24, text: 'Por isso o homem deixa o seu pai e a sua mãe e une-se à sua mulher, tornando-se uma só carne.' },
    { book: 'Colossenses', chapter: 3, verseStart: 14, text: 'Acima de tudo revesti-vos do amor, que é o vínculo da perfeição.' },
    { book: 'Provérbios', chapter: 31, verseStart: 10, text: 'Mulher virtuosa, quem a achará? O seu valor excede em muito ao de pedras preciosas.' },
    { book: 'Cântico dos Cânticos', chapter: 8, verseStart: 7, text: 'As muitas águas não poderiam apagar este amor, nem os rios afogá-lo.' },
    { book: 'Mateus', chapter: 19, verseStart: 6, text: 'Assim, já não são dois, mas uma só carne. O que Deus uniu, o homem não separe.' },
    { book: '1 Pedro', chapter: 4, verseStart: 8, text: 'Sobretudo, tende ardente amor uns para com os outros, porque o amor cobre multidão de pecados.' },
    { book: 'Tobias', chapter: 8, verseStart: 7, text: 'Senhor, tu sabes que não é por paixão que me caso, mas com a reta intenção de constituir família.' },
    { book: '1 Coríntios', chapter: 13, verseStart: 13, text: 'Agora permanecem estas três virtudes: a fé, a esperança e o amor; mas a maior delas é o amor.' },
    { book: 'Provérbios', chapter: 18, verseStart: 22, text: 'Quem encontra uma esposa acha uma coisa boa e alcança a benevolência do Senhor.' },
    { book: 'Efésios', chapter: 4, verseStart: 2, verseEnd: 3, text: 'Com toda a humildade e mansidão, com paciência, suportando-vos uns aos outros em amor.' },
  ],
  familia_filhos: [
    { book: 'Josué', chapter: 24, verseStart: 15, text: 'Eu e a minha casa serviremos ao Senhor.' },
    { book: 'Provérbios', chapter: 22, verseStart: 6, text: 'Educa a criança no caminho em que deve andar, e até quando envelhecer não se desviará dele.' },
    { book: 'Salmos', chapter: 127, verseStart: 3, text: 'Os filhos são herança do Senhor, e o fruto do ventre o seu galardão.' },
    { book: 'Efésios', chapter: 6, verseStart: 4, text: 'Pais, não irriteis vossos filhos, mas criai-os na disciplina e na instrução do Senhor.' },
    { book: 'Colossenses', chapter: 3, verseStart: 20, verseEnd: 21, text: 'Filhos, obedecei em tudo a vossos pais, pois isso é agradável ao Senhor.' },
    { book: 'Eclesiástico', chapter: 3, verseStart: 6, text: 'Quem honra seu pai terá vida longa; quem obedece ao Senhor confortará sua mãe.' },
    { book: 'Salmos', chapter: 128, verseStart: 3, text: 'Tua esposa será como videira frutífera no coração de tua casa; teus filhos, como rebentos de oliveira.' },
    { book: 'Provérbios', chapter: 17, verseStart: 6, text: 'Coroa dos velhos são os filhos dos filhos; e a glória dos filhos são seus pais.' },
    { book: '1 Timóteo', chapter: 5, verseStart: 8, text: 'Se alguém não cuida dos seus, e especialmente dos de sua família, negou a fé.' },
    { book: 'Êxodo', chapter: 20, verseStart: 12, text: 'Honra teu pai e tua mãe, para que se prolonguem os teus dias na terra que o Senhor te dá.' },
    { book: 'Provérbios', chapter: 1, verseStart: 8, verseEnd: 9, text: 'Ouve, filho meu, a instrução de teu pai e não rejeites o ensinamento de tua mãe.' },
    { book: 'Lucas', chapter: 2, verseStart: 51, verseEnd: 52, text: 'Jesus desceu com eles para Nazaré e era-lhes submisso. Crescia em sabedoria, estatura e graça.' },
  ],
  luto_ressurreicao: [
    { book: 'João', chapter: 11, verseStart: 25, verseEnd: 26, text: 'Eu sou a ressurreição e a vida. Quem crê em mim, ainda que morra, viverá.' },
    { book: '1 Tessalonicenses', chapter: 4, verseStart: 13, verseEnd: 14, text: 'Não queremos que sejais ignorantes a respeito dos que dormem, para não vos entristecerdes como os outros.' },
    { book: 'Sabedoria', chapter: 3, verseStart: 1, verseEnd: 3, text: 'As almas dos justos estão na mão de Deus, e nenhum tormento as tocará. Estão em paz.' },
    { book: 'Salmos', chapter: 116, verseStart: 15, text: 'Preciosa é aos olhos do Senhor a morte dos seus fiéis.' },
    { book: 'Romanos', chapter: 14, verseStart: 8, text: 'Se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. Quer vivamos quer morramos, somos do Senhor.' },
    { book: '1 Coríntios', chapter: 15, verseStart: 55, verseEnd: 57, text: 'Onde está, ó morte, a tua vitória? Graças a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo.' },
    { book: '2 Coríntios', chapter: 5, verseStart: 1, text: 'Sabemos que, se a nossa habitação terrestre se desfizer, temos de Deus um edifício eterno nos céus.' },
    { book: 'Filipenses', chapter: 1, verseStart: 21, text: 'Para mim o viver é Cristo, e o morrer é lucro.' },
    { book: 'Salmos', chapter: 23, verseStart: 4, text: 'Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo.' },
    { book: 'Apocalipse', chapter: 14, verseStart: 13, text: 'Felizes os mortos que desde agora morrem no Senhor. Sim, que descansem de suas fadigas.' },
    { book: 'Mateus', chapter: 5, verseStart: 4, text: 'Bem-aventurados os que choram, porque serão consolados.' },
    { book: 'Isaías', chapter: 25, verseStart: 8, text: 'O Senhor Deus aniquilará a morte para sempre e enxugará as lágrimas de todas as faces.' },
  ],
  saude_cura_cuidado: [
    { book: 'Jeremias', chapter: 17, verseStart: 14, text: 'Cura-me, Senhor, e serei curado; salva-me, e serei salvo, porque tu és o meu louvor.' },
    { book: 'Salmos', chapter: 103, verseStart: 2, verseEnd: 3, text: 'Bendiz, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios; Ele perdoa e sara.' },
    { book: 'Tiago', chapter: 5, verseStart: 14, verseEnd: 15, text: 'Está alguém enfermo? Chame os presbíteros da Igreja e orem sobre ele. A oração da fé salvará o doente.' },
    { book: 'Eclesiástico', chapter: 38, verseStart: 9, verseEnd: 12, text: 'Meu filho, não te descuides na doença: reza ao Senhor e Ele te curará; e dá lugar ao médico.' },
    { book: 'Mateus', chapter: 8, verseStart: 16, verseEnd: 17, text: 'Curou todos os que estavam doentes, para que se cumprisse o profeta: Ele tomou as nossas enfermidades.' },
    { book: 'Salmos', chapter: 41, verseStart: 4, text: 'O Senhor o sustentará no leito da dor; tu lhe restaurarás a saúde.' },
    { book: 'Lucas', chapter: 8, verseStart: 48, text: 'Filha, a tua fé te salvou; vai em paz e fica livre do teu mal.' },
    { book: 'Êxodo', chapter: 23, verseStart: 25, text: 'Servireis ao Senhor vosso Deus, e Ele abençoará o vosso pão e a vossa água; e tirará do meio de vós a enfermidade.' },
    { book: 'Isaías', chapter: 53, verseStart: 4, verseEnd: 5, text: 'Ele tomou sobre si as nossas enfermidades e carregou as nossas dores; por suas chagas fomos curados.' },
    { book: '3 João', chapter: 1, verseStart: 2, text: 'Amado, desejo que prosperes em tudo e tenhas saúde, assim como prospera a tua alma.' },
    { book: 'Salmos', chapter: 147, verseStart: 3, text: 'Ele cura os corações quebrantados e cuida de suas feridas.' },
    { book: '2 Coríntios', chapter: 4, verseStart: 16, text: 'Ainda que o nosso homem exterior se corrompa, o interior contudo se renova dia a dia.' },
  ],
  trabalho_vocacao: [
    { book: 'Colossenses', chapter: 3, verseStart: 23, verseEnd: 24, text: 'Tudo o que fizerdes, fazei-o de bom ânimo, como para o Senhor e não para os homens.' },
    { book: 'Provérbios', chapter: 16, verseStart: 3, text: 'Confia ao Senhor as tuas obras, e os teus projetos serão bem-sucedidos.' },
    { book: 'Salmos', chapter: 90, verseStart: 17, text: 'Seja sobre nós a graça do Senhor; confirma sobre nós a obra de nossas mãos.' },
    { book: '1 Coríntios', chapter: 15, verseStart: 58, text: 'Sede firmes e inabaláveis, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão.' },
    { book: 'Gálatas', chapter: 6, verseStart: 9, text: 'Não nos cansemos de fazer o bem, pois a seu tempo colheremos, se não desfalecermos.' },
    { book: 'Provérbios', chapter: 14, verseStart: 23, text: 'Em todo trabalho proveitoso há lucro, mas o mero tagarelar só conduz à penúria.' },
    { book: '2 Tessalonicenses', chapter: 3, verseStart: 10, verseEnd: 12, text: 'Trabalhai com tranquilidade para comer o vosso próprio pão.' },
    { book: 'Eclesiastes', chapter: 3, verseStart: 13, text: 'Que o homem coma, beba e desfrute do bem de todo o seu trabalho; isso é dom de Deus.' },
    { book: 'Mateus', chapter: 25, verseStart: 21, text: 'Muito bem, servo bom e fiel! Foste fiel no pouco, sobre o muito te colocarei. Entra no gozo do teu Senhor.' },
    { book: 'Efésios', chapter: 4, verseStart: 1, text: 'Rogo-vos que andeis de modo digno da vocação a que fostes chamados.' },
    { book: 'Jeremias', chapter: 29, verseStart: 11, text: 'Eu bem sei os pensamentos que tenho a vosso respeito, pensamentos de paz e não de mal, para vos dar um futuro e esperança.' },
    { book: 'Salmos', chapter: 128, verseStart: 2, text: 'Comerás do trabalho das tuas mãos; serás feliz e tudo te irá bem.' },
  ],
  dinheiro_providencia: [
    { book: 'Filipenses', chapter: 4, verseStart: 19, text: 'Meu Deus suprirá todas as vossas necessidades segundo a sua riqueza na glória, em Cristo Jesus.' },
    { book: 'Mateus', chapter: 6, verseStart: 25, verseEnd: 26, text: 'Olhai as aves do céu: não semeiam nem ceifam, e vosso Pai celeste as sustenta. Não valeis vós muito mais?' },
    { book: '1 Timóteo', chapter: 6, verseStart: 6, verseEnd: 8, text: 'Grande fonte de lucro é a piedade com o contentamento. Tendo sustento e com que nos vestir, estejamos contentes.' },
    { book: 'Hebreus', chapter: 13, verseStart: 5, text: 'Seja a vossa vida sem avareza, contentando-vos com o que tendes, pois Ele disse: Não te deixarei nem desampararei.' },
    { book: 'Provérbios', chapter: 11, verseStart: 24, verseEnd: 25, text: 'O que espalha com generosidade enriquece; a alma generosa prosperará.' },
    { book: 'Salmos', chapter: 37, verseStart: 25, text: 'Fui jovem e já sou velho, mas nunca vi desamparado o justo, nem a sua descendência a mendigar o pão.' },
    { book: 'Lucas', chapter: 12, verseStart: 15, text: 'Guardai-vos de toda a avareza, porque a vida de uma pessoa não consiste na abundância dos bens que possui.' },
    { book: '2 Coríntios', chapter: 9, verseStart: 7, verseEnd: 8, text: 'Cada um dê segundo propôs no seu coração; Deus ama quem dá com alegria e é poderoso para cumular-vos de graça.' },
    { book: 'Provérbios', chapter: 22, verseStart: 1, text: 'Mais vale o bom nome do que muitas riquezas; a boa reputação vale mais que a prata e o ouro.' },
    { book: 'Eclesiástico', chapter: 29, verseStart: 1, verseEnd: 2, text: 'Quem usa de misericórdia empresta ao próximo, e quem o socorre guarda os mandamentos.' },
    { book: 'Malaquias', chapter: 3, verseStart: 10, text: 'Trazei todos os dízimos à casa do tesouro e provai-me nisto, se não vos abrir as janelas do céu com bênçãos.' },
    { book: 'Salmos', chapter: 34, verseStart: 11, text: 'Os leões passam necessidade e fome, mas aos que buscam o Senhor nenhum bem faltará.' },
  ],
  perdao_misericordia: [
    { book: 'Efésios', chapter: 4, verseStart: 32, text: 'Sede bondosos e compassivos uns para com os outros, perdoando-vos mutuamente, como Deus vos perdoou em Cristo.' },
    { book: 'Colossenses', chapter: 3, verseStart: 13, text: 'Suportai-vos uns aos outros e perdoai-vos mutuamente; assim como o Senhor vos perdoou, perdoai vós também.' },
    { book: '1 João', chapter: 1, verseStart: 9, text: 'Se confessamos os nossos pecados, Ele é fiel e justo para nos perdoar e nos purificar de toda injustiça.' },
    { book: 'Salmos', chapter: 103, verseStart: 11, verseEnd: 12, text: 'Quanto dista o oriente do ocidente, tanto afasta de nós as nossas transgressões.' },
    { book: 'Miqueias', chapter: 7, verseStart: 18, verseEnd: 19, text: 'Quem é Deus semelhante a ti, que perdoas a iniquidade? Lançarás todos os nossos pecados nas profundezas do mar.' },
    { book: 'Mateus', chapter: 18, verseStart: 21, verseEnd: 22, text: 'Senhor, quantas vezes perdoarei a meu irmão? Até sete vezes? Jesus respondeu: Não até sete, mas setenta vezes sete.' },
    { book: 'Lucas', chapter: 6, verseStart: 37, text: 'Não julgueis e não sereis julgados; perdoai e sereis perdoados.' },
    { book: 'Isaías', chapter: 1, verseStart: 18, text: 'Ainda que os vossos pecados sejam como o escarlate, eles se tornarão brancos como a neve.' },
    { book: 'Mateus', chapter: 6, verseStart: 14, verseEnd: 15, text: 'Se perdoardes aos homens as suas ofensas, também vosso Pai celeste vos perdoará.' },
    { book: 'Salmos', chapter: 51, verseStart: 3, verseEnd: 4, text: 'Tem misericórdia de mim, ó Deus, segundo a tua bondade; apaga as minhas transgressões.' },
    { book: 'Lucas', chapter: 15, verseStart: 20, text: 'Estando ele ainda longe, o pai o viu e, cheio de compaixão, correu, lançou-se-lhe ao pescoço e o beijou.' },
    { book: 'Provérbios', chapter: 28, verseStart: 13, text: 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.' },
  ],
  mansidao_pacificacao: [
    { book: 'Tiago', chapter: 1, verseStart: 19, verseEnd: 20, text: 'Todo homem seja pronto para ouvir, tardio para falar, tardio para se irar; a ira do homem não produz a justiça de Deus.' },
    { book: 'Provérbios', chapter: 15, verseStart: 1, text: 'A resposta branda desvia o furor, mas a palavra dura suscita a ira.' },
    { book: 'Efésios', chapter: 4, verseStart: 26, verseEnd: 27, text: 'Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira, nem deis lugar ao diabo.' },
    { book: 'Mateus', chapter: 5, verseStart: 9, text: 'Bem-aventurados os pacificadores, porque serão chamados filhos de Deus.' },
    { book: 'Romanos', chapter: 12, verseStart: 17, verseEnd: 18, text: 'A ninguém pagueis mal por mal. Se for possível, quanto depender de vós, tende paz com todos os homens.' },
    { book: 'Provérbios', chapter: 16, verseStart: 32, text: 'Melhor é o homem paciente do que o guerreiro, e quem domina o seu espírito do que aquele que conquista uma cidade.' },
    { book: 'Gálatas', chapter: 5, verseStart: 22, verseEnd: 23, text: 'O fruto do Espírito é: caridade, alegria, paz, paciência, amabilidade, bondade, lealdade, mansidão, domínio de si.' },
    { book: 'Colossenses', chapter: 4, verseStart: 6, text: 'A vossa palavra seja sempre agradável, temperada com sal, para saberdes como responder a cada um.' },
    { book: 'Tiago', chapter: 3, verseStart: 17, verseEnd: 18, text: 'A sabedoria do alto é pura, pacífica, moderada, tratável, cheia de misericórdia e de bons frutos.' },
    { book: 'Salmos', chapter: 37, verseStart: 8, text: 'Deixa a ira e abandona o furor; não te impacientes, pois isso só leva ao mal.' },
    { book: 'Provérbios', chapter: 12, verseStart: 18, text: 'Há quem fale precipitadamente como golpes de espada, mas a língua dos sábios traz a cura.' },
    { book: '1 Pedro', chapter: 3, verseStart: 9, text: 'Não retribuais mal por mal, nem injúria por injúria; pelo contrário, bendizei.' },
  ],
  libertacao_disciplina: [
    { book: '1 Coríntios', chapter: 10, verseStart: 13, text: 'Não vos sobreveio tentação que não fosse humana; e Deus é fiel e proverá o livramento para suportardes.' },
    { book: 'Gálatas', chapter: 5, verseStart: 1, text: 'Foi para a liberdade que Cristo nos libertou. Permanecei firmes e não vos submetais de novo ao jugo da escravidão.' },
    { book: 'Romanos', chapter: 6, verseStart: 14, text: 'O pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça.' },
    { book: 'João', chapter: 8, verseStart: 36, text: 'Se o Filho vos libertar, sereis verdadeiramente livres.' },
    { book: 'Filipenses', chapter: 4, verseStart: 13, text: 'Tudo posso naquele que me fortalece.' },
    { book: 'Tiago', chapter: 4, verseStart: 7, text: 'Sujeitai-vos a Deus, resisti ao diabo, e ele fugirá de vós.' },
    { book: '1 Coríntios', chapter: 6, verseStart: 12, text: 'Tudo me é lícito, mas nem tudo me convém. Tudo me é lícito, mas eu não me deixarei dominar por coisa alguma.' },
    { book: 'Provérbios', chapter: 25, verseStart: 28, text: 'Como cidade derrubada e sem muros, assim é o homem que não pode conter o seu espírito.' },
    { book: 'Tito', chapter: 2, verseStart: 11, verseEnd: 12, text: 'A graça de Deus manifestou-se, ensinando-nos a renunciar à impiedade e a viver com moderação, justiça e piedade.' },
    { book: 'Salmos', chapter: 119, verseStart: 133, text: 'Firma os meus passos na tua palavra, e não permitas que nenhuma iniquidade me domine.' },
    { book: '2 Timóteo', chapter: 1, verseStart: 7, text: 'Pois Deus não nos deu um espírito de covardia, mas de poder, de amor e de moderação.' },
    { book: 'Efésios', chapter: 6, verseStart: 10, verseEnd: 11, text: 'Fortalecei-vos no Senhor e na força do seu poder. Revesti-vos de toda a armadura de Deus.' },
  ],
  oracao_intimidade_deus: [
    { book: 'Jeremias', chapter: 33, verseStart: 3, text: 'Clama a mim, e responder-te-ei, e anunciar-te-ei coisas grandes e firmes que não sabes.' },
    { book: 'Salmos', chapter: 63, verseStart: 2, verseEnd: 4, text: 'Ó Deus, tu és o meu Deus, de madrugada te buscarei; a minha alma tem sede de ti.' },
    { book: 'Mateus', chapter: 6, verseStart: 6, text: 'Quando orares, entra no teu quarto, fecha a porta e ora a teu Pai em segredo; e teu Pai te recompensará.' },
    { book: 'Lucas', chapter: 18, verseStart: 1, text: 'Contou-lhes uma parábola sobre o dever de orar sempre e nunca desanimar.' },
    { book: '1 João', chapter: 5, verseStart: 14, text: 'Esta é a confiança que temos nele: se pedirmos alguma coisa segundo a sua vontade, Ele nos ouve.' },
    { book: 'Salmos', chapter: 145, verseStart: 18, text: 'Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.' },
    { book: 'Romanos', chapter: 8, verseStart: 26, text: 'O Espírito ajuda a nossa fraqueza; não sabemos o que havemos de pedir, mas o Espírito intercede por nós.' },
    { book: 'Salmos', chapter: 27, verseStart: 8, text: 'O meu coração disse: Buscai a minha face; a tua face, Senhor, eu buscarei.' },
    { book: 'Hebreus', chapter: 4, verseStart: 16, text: 'Aproximemo-nos com confiança do trono da graça, a fim de alcançarmos misericórdia e auxílio oportuno.' },
    { book: 'Salmos', chapter: 100, verseStart: 4, text: 'Entrai pelas suas portas com ações de graças e nos seus átrios com louvor; bendizei o seu nome.' },
    { book: 'Marcos', chapter: 11, verseStart: 24, text: 'Tudo quanto em oração pedirdes, crede que recebestes, e ser-vos-á concedido.' },
    { book: 'Salmos', chapter: 116, verseStart: 1, verseEnd: 2, text: 'Amo o Senhor, porque Ele ouve a minha voz e as minhas súplicas; a Ele invocarei toda a minha vida.' },
  ],
  justica_protecao: [
    { book: 'Miqueias', chapter: 6, verseStart: 8, text: 'Ele te declarou, ó homem, o que é bom: que pratiques a justiça, ames a misericórdia e andes humildemente com Deus.' },
    { book: 'Salmos', chapter: 82, verseStart: 3, verseEnd: 4, text: 'Fazei justiça ao fraco e ao órfão; defendei os direitos dos aflitos e desamparados.' },
    { book: 'Isaías', chapter: 1, verseStart: 17, text: 'Aprendei a fazer o bem; procurai a justiça, socorrei o oprimido, fazei justiça ao órfão, defendei a viúva.' },
    { book: 'Provérbios', chapter: 31, verseStart: 8, verseEnd: 9, text: 'Abre a tua boca a favor do mudo, pelo direito de todos os desamparados; julga retamente.' },
    { book: 'Tiago', chapter: 1, verseStart: 27, text: 'A religião pura e imaculada diante de Deus é esta: visitar os órfãos e as viúvas nas suas tribulações.' },
    { book: 'Salmos', chapter: 146, verseStart: 7, verseEnd: 9, text: 'O Senhor faz justiça aos oprimidos, dá pão aos famintos e liberta os encarcerados.' },
    { book: 'Amós', chapter: 5, verseStart: 24, text: 'Corra, porém, a justiça como as águas, e a retidão como um ribeiro perene.' },
    { book: 'Mateus', chapter: 25, verseStart: 40, text: 'Em verdade vos digo que, quantas vezes o fizestes a um destes meus irmãos mais pequeninos, a mim o fizestes.' },
    { book: 'Salmos', chapter: 72, verseStart: 12, verseEnd: 13, text: 'Ele livrará o necessitado que clama, o aflito que não tem quem o ajude; terá compaixão do pobre.' },
    { book: 'Provérbios', chapter: 14, verseStart: 31, text: 'O que oprime o pobre insulta o seu Criador, mas honra-o quem se compadece do necessitado.' },
    { book: 'Lucas', chapter: 4, verseStart: 18, text: 'O Espírito do Senhor está sobre mim, para anunciar a boa-nova aos pobres e proclamar a libertação aos cativos.' },
    { book: 'Romanos', chapter: 12, verseStart: 21, text: 'Não te deixes vencer pelo mal, mas vence o mal com o bem.' },
  ],
  decisao_discernimento: [
    { book: 'Tiago', chapter: 1, verseStart: 5, text: 'Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá generosamente.' },
    { book: 'Provérbios', chapter: 3, verseStart: 5, verseEnd: 6, text: 'Confia no Senhor de todo o coração; reconhece-o em todos os teus caminhos, e Ele endireitará as tuas veredas.' },
    { book: 'Salmos', chapter: 119, verseStart: 105, text: 'Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.' },
    { book: 'Salmos', chapter: 32, verseStart: 8, text: 'Instruir-te-ei e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus olhos.' },
    { book: 'Isaías', chapter: 30, verseStart: 21, text: 'Os teus ouvidos ouvirão a palavra que atrás de ti dirá: Este é o caminho, andai por ele.' },
    { book: 'Provérbios', chapter: 16, verseStart: 9, text: 'O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.' },
    { book: 'Salmos', chapter: 25, verseStart: 4, verseEnd: 5, text: 'Faze-me conhecer os teus caminhos, Senhor; ensina-me as tuas veredas e guia-me na tua verdade.' },
    { book: 'Romanos', chapter: 12, verseStart: 2, text: 'Transformai-vos pela renovação da vossa mente, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.' },
    { book: 'Eclesiastes', chapter: 3, verseStart: 1, text: 'Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.' },
    { book: 'Lucas', chapter: 14, verseStart: 28, text: 'Quem de vós, querendo construir uma torre, não se assenta primeiro a calcular as despesas para ver se tem com que a acabar?' },
    { book: 'Salmos', chapter: 37, verseStart: 5, text: 'Entrega o teu caminho ao Senhor; confia nele, e Ele tudo fará.' },
    { book: 'Filipenses', chapter: 1, verseStart: 9, verseEnd: 10, text: 'Peço que o vosso amor cresça mais e mais em conhecimento e discernimento, para aprovar as coisas excelentes.' },
  ],
};
